[local]
localhost

[mongodb]
mongodb.bmkrishtech.online

[redis]
redis.bmkrishtech.online

[mysql]
mysql.bmkrishtech.online

[rabbitmq]
rabbitmq.bmkrishtech.online

[catalogue]
catalogue.bmkrishtech.online

[user]
user.bmkrishtech.online

[cart]
cart.bmkrishtech.online

[shipping]
shipping.bmkrishtech.online

[payment]
payment.bmkrishtech.online

[frontend]
frontend.bmkrishtech.online